version: 0.2

phases:
    build:
        commands:
            - cd SX.SB.Lam.Quote
            - dotnet new -i Amazon.Lambda.Templates::*
            - dotnet tool install -g Amazon.Lambda.Tools
            - dotnet tool update -g Amazon.Lambda.Tools
            - dotnet lambda deploy-function "SX-SB-Lam-Quote-$STAGE" --function-role "arn:aws:iam::$ACCOUNT_ID:role/SX-SB-Lam-Quote" --region "$AWS_REGION"
    