version: 0.2

phases:
    build:
        commands: 
            - cd SX.SB.Lam.Quote
            - dotnet new -i Amazon.Lambda.Templates::*
            - dotnet tool install -g Amazon.Lambda.Tools
            - dotnet tool update -g Amazon.Lambda.Tools
            - dotnet lambda deploy-function "netsix" --function-role "arn:aws:iam::362122011912:role/accounts" --region "$AWS_REGION"
    